apiVersion: apps/v1
kind: Deployment
metadata:
  name: courier-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: courier-service
  template:
    metadata:
      labels:
        app: courier-service
    spec:
      containers:
      - name: courier-service
        image: logistik-microservice-courier-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10